// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Rectangle;

    return Rectangle = (function() {
      function Rectangle() {}

      /*
      @todo consider angle
      */


      Rectangle.isPointInside = function(point, pos, size, angle) {
        return (Math.abs(pos.x - point.x) < size.x / 2) && (Math.abs(pos.y - point.y) < size.y / 2);
      };

      return Rectangle;

    })();
  });

}).call(this);
